// apps/react-starter/src/pages/overview/components/status-history/index.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import styles from "./styles.module.css";

import { IxCard, IxCardContent, IxTypography } from "@siemens/ix-react";
import { getComputedCSSProperty } from "@siemens/ix-echarts";
import ReactEcharts from "echarts-for-react";
import { useTranslation } from "react-i18next";
import { useRef, useState } from "react";
import { useResizeHandler } from "../../../../util/util.ts";
import EChartsReact from "echarts-for-react";
import { useEChartsTheme } from "@/hooks/theme.ts";
import { ECBasicOption } from "echarts/types/dist/shared";

const seriesOnline = {
  name: "Online",
  color: [getComputedCSSProperty("color-success")],
  data: [{ value: 60 }, { value: 75 }, { value: 100 }, { value: 60 }, { value: 75 }, { value: 60 }],
};

const seriesOffline = {
  name: "Offline",
  color: [getComputedCSSProperty("color-neutral")],
  data: [
    { value: -30 },
    { value: -62 },
    { value: -25 },
    { value: -61 },
    { value: -99 },
    { value: -60 },
  ],
};

const seriesErrors = {
  name: "Errors",
  color: getComputedCSSProperty("color-alarm"),
  data: [
    { value: 0 },
    { value: 17 },
    { value: -39 },
    { value: -60 },
    { value: -20 },
    { value: -2 },
  ],
};

function getOption(): ECBasicOption {
  return {
    grid: {
      top: 10,
      bottom: 85,
      left: 40,
      right: 10,
    },
    legend: {
      orient: "horizontal",
      icon: "rect",
      left: "1",
      bottom: -0,
    },
    xAxis: {
      data: ["Jan", "Feb", "Mar", "Apr", "May", "Jun"],
      boundaryGap: false, // Ensure the first label starts at the beginning
      splitLine: {
        show: true,
      },
    },
    yAxis: {
      splitLine: {
        show: true,
      },
    },
    series: [
      {
        type: "line",
        ...seriesOnline,
      },
      {
        type: "line",
        ...seriesErrors,
      },
      {
        type: "line",
        ...seriesOffline,
      },
    ],
  };
}

function StatusHistory() {
  const { t } = useTranslation();
  const [option] = useState<ECBasicOption>(getOption());
  const chartRef = useRef<EChartsReact>(null);
  const theme = useEChartsTheme();
  useResizeHandler(chartRef);

  return (
    <IxCard className={styles.StatusHistory}>
      <IxCardContent>
        <IxTypography format="label" bold>
          {t("status-history.title")}
        </IxTypography>
        <ReactEcharts
          ref={chartRef}
          onChartReady={(echarts) => setTimeout(echarts.resize)}
          className={styles.echarts}
          option={option}
          theme={theme}
        />
      </IxCardContent>
    </IxCard>
  );
}

export default StatusHistory;

// apps/vue-starter/src/components/Overview/StatusHistory.vue
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

<script setup lang="ts">
import { ref, computed, onUnmounted } from "vue";
import { themeSwitcher } from "@siemens/ix";
import { IxCard, IxCardContent, IxTypography } from "@siemens/ix-vue";
import { registerTheme, getComputedCSSProperty } from "@siemens/ix-echarts";
import type { EChartsOption } from "echarts";
import VueECharts from "vue-echarts";
import * as echarts from "echarts/core";
import * as charts from "echarts/charts";
import * as components from "echarts/components";
import * as renderer from "echarts/renderers";
import { useI18n } from "vue-i18n";
import { useChart } from "../../composables/useChart";
import { CHART_CONSTANTS, getStatusHistoryData } from "../../composables/chartConfig";

registerTheme(echarts);
echarts.use([
  components.TooltipComponent,
  components.LegendComponent,
  components.GridComponent,
  components.MarkLineComponent,
  charts.LineChart,
  renderer.CanvasRenderer,
]);

const { t } = useI18n();
const chartRef = ref();
const theme = ref(themeSwitcher.getCurrentTheme());
const chartData = getStatusHistoryData();

const chartOption = computed((): EChartsOption => {
  const series = Object.values(chartData.series).map(seriesData => ({
    type: "line" as const,
    name: seriesData.name,
    color: getComputedCSSProperty(seriesData.colorKey),
    data: seriesData.data,
  }));
  return {
    grid: CHART_CONSTANTS.GRID.STATUS_HISTORY,
    legend: {
      orient: "horizontal" as const,
      icon: "rect" as const,
      left: "1",
      bottom: 0,
    },
    xAxis: {
      data: chartData.months,
      boundaryGap: false,
      splitLine: { show: true },
    },
    yAxis: {
      splitLine: { show: true },
    },
    series,
  };
});

useChart({
  chartRef,
  initializeChart: async () => {}
});

const themeChangeHandler = (newTheme: string) => {
  const root = document.documentElement;
  Array.from(root.classList)
    .filter(cls => cls.startsWith("theme-"))
    .forEach(cls => root.classList.remove(cls));
  root.classList.add(newTheme);
  theme.value = newTheme;
};

themeSwitcher.themeChanged.on(themeChangeHandler);
onUnmounted(() => {
  themeSwitcher.themeChanged.off(themeChangeHandler);
});
</script>

<template>
  <IxCard class="status-history">
    <IxCardContent>
      <IxTypography format="label" bold>{{ t('status-history.title') }}</IxTypography>
      <VueECharts ref="chartRef" class="charts" :theme="theme" :option="chartOption" autoresize
        :init-options="{ renderer: CHART_CONSTANTS.RENDERER }" />
    </IxCardContent>
  </IxCard>
</template>

<style scoped>
.status-history {
  height: v-bind('CHART_CONSTANTS.DIMENSIONS.height');
  min-height: v-bind('CHART_CONSTANTS.DIMENSIONS.minHeight');
  max-height: v-bind('CHART_CONSTANTS.DIMENSIONS.maxHeight');
}

.charts {
  position: relative;
  width: 100%;
  height: 100%;
  padding-top: 1rem;
}
</style>
