// apps/vue-starter/src/components/Overview/IncidentList.vue
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

<script setup lang="ts">
import { computed } from "vue";
import { useI18n } from "vue-i18n";
import { showDemoModal } from "@/helpers/modal";
import { useIsMobileViewPort } from "@/composables/useMediaQuery";
import type { Incident } from "./incident";
import {
  IxLayoutGrid,
  IxTypography,
  IxRow,
  IxCol,
  IxIcon,
  IxEventListItem,
  IxEventList,
  IxButton,
  IxIconButton,
} from "@siemens/ix-vue";
import { addIcons } from '@siemens/ix-icons';
import {
  iconCloudUpload,
  iconMaintenanceWarning,
  iconInfo,
  iconError,
  iconOpenExternal,
  iconUpload
} from '@siemens/ix-icons/icons';

addIcons({
  'cloud-upload': iconCloudUpload,
  'maintenance-warning': iconMaintenanceWarning,
  'info': iconInfo,
  'error': iconError,
  'open-external': iconOpenExternal,
  'upload': iconUpload
});

const { t } = useI18n();
const isMobile = useIsMobileViewPort();

const handleDemoModal = () => {
  showDemoModal(t);
};

const props = defineProps<{
  incidents: Incident[];
  search: string;
}>();

const filteredIncidents = computed(() => {
  if (!props.search) {
    return props.incidents;
  }

  const query = props.search.toLowerCase();
  return props.incidents.filter(incident =>
    typeof incident.deviceName === "string" && incident.deviceName.toLowerCase().includes(query)
  );
});
</script>

<template>
  <section class="incident-list">
    <IxLayoutGrid :no-margin="true">
      <IxRow class="eventlist-headeroffset">
        <IxCol size="3" sizeSm="6">
          <IxRow style="gap: 1rem">
            <IxTypography format="label" bold text-color="soft">
              Type
            </IxTypography>
            <IxTypography format="label" bold text-color="soft">
              Incident name
            </IxTypography>
          </IxRow>
        </IxCol>
        <IxCol size="3" sizeSm="4">
          <IxTypography format="label" bold text-color="soft" class="titleoffset-device">
            Device
          </IxTypography>
        </IxCol>
        <IxCol size="3" class="desktop">
          <IxTypography format="label" bold text-color="soft" class="titleOffset-date">
            Date
          </IxTypography>
        </IxCol>
      </IxRow>
    </IxLayoutGrid>
    <IxEventList :itemHeight="72" :animated="false" class="event-list">
      <IxEventListItem v-for="incident in filteredIncidents" :key="incident.id" :itemColor="'color-' + incident.color"
        data-testid="incident-item">
        <!-- Desktop Layout -->
        <IxLayoutGrid v-if="!isMobile" :noMargin="true">
          <IxRow>
            <IxCol size="3">
              <IxRow style="gap: 1rem" class="no-wrap">
                <IxIcon :name="incident.icon" size="24" />
                <IxTypography bold>{{ incident.incidentName }}</IxTypography>
              </IxRow>
              <IxRow>
                <IxTypography class="info-text" textColor="soft">{{
                  incident.infoText
                  }}</IxTypography>
              </IxRow>
            </IxCol>
            <IxCol size="3">
              <IxTypography bold>{{ incident.deviceName }}</IxTypography>
              <IxTypography textColor="soft">{{ incident.ipAddress }}</IxTypography>
            </IxCol>
            <IxCol>
              <IxTypography textColor="soft">{{ incident.date }}</IxTypography>
              <IxTypography textColor="soft">{{ incident.time }}</IxTypography>
            </IxCol>
            <IxCol class="incident-actions">
              <IxIconButton variant="secondary" ghost :icon="iconOpenExternal" />
              <IxButton outline color="primary" @click="handleDemoModal">{{ t("incidents.create-task") }}</IxButton>
            </IxCol>
          </IxRow>
        </IxLayoutGrid>

        <!-- Mobile Layout -->
        <IxLayoutGrid v-else :noMargin="true">
          <IxRow>
            <IxCol size="6">
              <IxRow style="gap: 1rem" class="no-wrap">
                <IxIcon :name="incident.icon" size="24" />
                <IxTypography bold>{{ incident.incidentName }}</IxTypography>
              </IxRow>
              <IxRow>
                <IxTypography class="info-text" textColor="soft">{{
                  incident.infoText
                  }}</IxTypography>
              </IxRow>
            </IxCol>
            <IxCol size="4">
              <IxTypography bold>{{ incident.deviceName }}</IxTypography>
              <IxTypography textColor="soft">{{ incident.ipAddress }}</IxTypography>
            </IxCol>
            <IxCol size="2">
              <IxIconButton variant="primary" outline :icon="iconUpload" @click="handleDemoModal" />
            </IxCol>
          </IxRow>
        </IxLayoutGrid>
      </IxEventListItem>
    </IxEventList>
  </section>
</template>

<style scoped>
.no-wrap {
  flex-wrap: nowrap;
}

.incident-list {
  display: flex;
  flex-direction: column;
  height: 100%;
  overflow: hidden;
}

.event-list {
  overflow: auto;
  height: 100%;
  position: relative;
}

.eventlist-headeroffset {
  padding-left: 1.125rem;
}

.incident-actions {
  display: flex;
  flex-wrap: nowrap;
  gap: 0.5rem;
  justify-content: flex-end;
  align-items: center;
}

.info-text {
  padding-left: 2.5rem;
  overflow: hidden;
  text-overflow: ellipsis;
}

/* Responsive styles */
@media (max-width: 48em) {
  .desktop {
    display: none;
  }
}
</style>

// apps/angular-starter/src/app/pages/overview/components/incidents/incident-list/incident-list.component.ts
import { Component, Input } from '@angular/core';
import {
  iconCloudUpload,
  iconMaintenanceWarning,
  iconInfo,
  iconError,
  iconOpenExternal,
} from '@siemens/ix-icons/icons';
import { addIcons } from '@siemens/ix-icons';
import {
  IxLayoutGrid,
  IxRow,
  IxCol,
  IxEventList,
  IxEventListItem,
  IxTypography,
  IxIcon,
  IxIconButton,
  IxButton,
} from '@siemens/ix-angular/standalone';
import { useShowDemoMessage } from '../../../../../shared/utlis';
import { TranslateModule } from '@ngx-translate/core';

@Component({
  selector: 'app-incident-list',
  standalone: true,
  imports: [
    IxLayoutGrid,
    IxRow,
    IxCol,
    IxEventList,
    IxEventListItem,
    IxTypography,
    IxIcon,
    IxIconButton,
    IxButton,
    TranslateModule,
  ],
  templateUrl: './incident-list.component.html',
  styleUrl: './incident-list.component.scss',
})
export class IncidentListComponent {
  @Input() incidents: any[] = [];
  @Input() search = '';

  constructor() {
    addIcons({
      iconCloudUpload,
      iconMaintenanceWarning,
      iconInfo,
      iconError,
      iconOpenExternal,
    });
  }

  usemodal() {
    useShowDemoMessage();
  }
  get filteredIncidents() {
    const query = this.search.toLowerCase();
    return this.incidents.filter((incident) =>
      Object.values(incident).some(
        (value) =>
          typeof value === 'string' && value.toLowerCase().includes(query),
      ),
    );
  }
}

<section class="incident-list">
  <ix-layout-grid noMargin>
    <ix-row class="event-list-header-offset">
      <ix-col size="3" sizeSm="6">
        <ix-row style="gap: 1rem">
          <ix-typography format="label" bold textColor="soft">
            {{ "incidents.incident-cards.type" | translate }}
          </ix-typography>
          <ix-typography format="label" bold textColor="soft">
            Incident name
          </ix-typography>
        </ix-row>
      </ix-col>
      <ix-col size="3" sizeSm="4">
        <ix-typography
          format="label"
          bold
          textColor="soft"
          class="title-offset-device"
        >
          {{ "incidents.incident-cards.device" | translate }}
        </ix-typography>
      </ix-col>
      <ix-col size="3" class="desktop">
        <ix-typography
          format="label"
          bold
          textColor="soft"
          class="title-offset-date"
        >
          {{ "incidents.incident-cards.date" | translate }}
        </ix-typography>
      </ix-col>
    </ix-row>
  </ix-layout-grid>
  <ix-event-list [itemHeight]="72" [animated]="false" class="event-list">
    @for (incident of filteredIncidents; track incident.id) {
      <ix-event-list-item [itemColor]="'color-' + incident.color">
        <!-- Mobile Layout -->
        @if (mediaQueryService.isMobile$ | async) {
          <ix-layout-grid noMargin>
            <ix-row>
              <ix-col size="6">
                <ix-row style="gap: 1rem" class="no-wrap">
                  <ix-icon [name]="incident.icon" size="24"></ix-icon>
                  <ix-typography bold>
                    {{ incident.incidentName }}
                  </ix-typography>
                </ix-row>
                <ix-row>
                  <ix-typography class="info-text" textColor="soft">
                    {{ incident.infoText }}
                  </ix-typography>
                </ix-row>
              </ix-col>
              <ix-col size="4">
                <ix-typography bold>
                  {{ incident.deviceName }}
                </ix-typography>
                <ix-typography textColor="soft">
                  {{ incident.ipAddress }}
                </ix-typography>
              </ix-col>
              <ix-col size="2">
                <ix-icon-button
                  variant="primary"
                  outline
                  icon="upload"
                  (click)="usemodal()"
                ></ix-icon-button>
              </ix-col>
            </ix-row>
          </ix-layout-grid>
        } @else {
          <!-- Desktop Layout -->
          <ix-layout-grid noMargin>
            <ix-row>
              <ix-col size="3">
                <ix-row style="gap: 1rem" class="no-wrap">
                  <ix-icon [name]="incident.icon" size="24"></ix-icon>
                  <ix-typography bold>
                    {{ incident.incidentName }}
                  </ix-typography>
                </ix-row>
                <ix-row>
                  <ix-typography class="info-text" textColor="soft">
                    {{ incident.infoText }}
                  </ix-typography>
                </ix-row>
              </ix-col>

              <ix-col size="3">
                <ix-typography bold>
                  {{ incident.deviceName }}
                </ix-typography>
                <ix-typography textColor="soft">
                  {{ incident.ipAddress }}
                </ix-typography>
              </ix-col>

              <ix-col>
                <ix-typography textColor="soft">
                  {{ incident.date }}
                </ix-typography>
                <ix-typography textColor="soft">
                  {{ incident.time }}
                </ix-typography>
              </ix-col>

              <ix-col class="incident-actions">
                <ix-icon-button
                  variant="secondary"
                  ghost
                  icon="open-external"
                ></ix-icon-button>
                <ix-button outline color="primary" (click)="usemodal()">
                  {{ "incidents.create-task" | translate }}
                </ix-button>
              </ix-col>
            </ix-row>
          </ix-layout-grid>
        }
      </ix-event-list-item>
    } @empty {
      <div>No items found.</div>
    }
  </ix-event-list>
</section>
