// apps/legacy-angular-starter/src/app/pages/devices/components/delete-modal/delete-modal.component.ts
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Component, inject, Inject } from '@angular/core';
import {
  IxButton,
  IxModalContent,
  IxModalFooter,
  IxModalHeader,
  IxActiveModal,
} from '@siemens/ix-angular/standalone';
import { TranslateModule } from '@ngx-translate/core';
import { addIcons } from '@siemens/ix-icons';
import { iconTrashcan } from '@siemens/ix-icons/icons';

@Component({
  selector: 'app-delete-modal',
  standalone: true,
  imports: [
    IxModalHeader,
    IxModalContent,
    IxModalFooter,
    IxButton,
    TranslateModule,
  ],
  templateUrl: './delete-modal.component.html',
  styleUrl: './delete-modal.component.scss',
})
export class DeleteModalComponent {
  @Inject(IxActiveModal) readonly activeModal = inject(IxActiveModal);

  constructor() {
    addIcons({
      iconTrashcan,
    });
  }

  close() {
    this.activeModal.close({ deleted: true });
  }

  dismiss() {
    this.activeModal.dismiss({ deleted: false });
  }
}

<ix-modal-header
  icon="trashcan"
  icon-color="color-alarm"
  (closeClick)="dismiss()"
>
  {{ "device-delete-modal.title" | translate }}
</ix-modal-header>
<ix-modal-content>{{
  "device-delete-modal.content" | translate
}}</ix-modal-content>
<ix-modal-footer>
  <ix-button
    variant="subtle-secondary"
    (click)="dismiss()"
    (keydown.enter)="dismiss()"
  >
    {{ "device-delete-modal.dismiss" | translate }}
  </ix-button>
  <ix-button
    variant="danger-primary"
    type="button"
    (click)="close()"
    (keydown.enter)="close()"
  >
    {{ "device-delete-modal.close" | translate }}
  </ix-button>
</ix-modal-footer>

// apps/react-starter/src/pages/devices/components/ag-grid-table/delete-modal.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { useRef } from "react";
import {
  IxButton,
  IxModalContent,
  IxModalFooter,
  IxModalHeader,
  Modal,
  ModalRef,
} from "@siemens/ix-react";
import { iconTrashcan } from "@siemens/ix-icons/icons";
import { useTranslation } from "react-i18next";

export default function DeleteModal() {
  const { t } = useTranslation();
  const modalRef = useRef<ModalRef>(null);

  const close = () => {
    modalRef.current?.close({ deleted: true });
  };
  const dismiss = () => {
    modalRef.current?.dismiss({ deleted: false });
  };

  return (
    <Modal ref={modalRef}>
      <IxModalHeader onCloseClick={() => dismiss()} icon={iconTrashcan} iconColor="color-alarm">
        {t("device-delete-modal.title")}
      </IxModalHeader>
      <IxModalContent> {t("device-delete-modal.content")}</IxModalContent>
      <IxModalFooter>
        <IxButton variant="subtle-secondary" onClick={() => dismiss()}>
          {t("device-delete-modal.dismiss")}
        </IxButton>
        <IxButton variant="danger-primary" onClick={() => close()}>
          {t("device-delete-modal.close")}
        </IxButton>
      </IxModalFooter>
    </Modal>
  );
}
