// apps/legacy-react-starter/src/pages/application-settings/index.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxToggle, IxTypography, IxUpload } from "@siemens/ix-react";
import styles from "./styles.module.css";
import { useTranslation } from "react-i18next";

export default function ApplicationSettings() {
  const { t } = useTranslation();
  return (
    <section className={styles.ApplicationSettings}>
      <section>
        <IxTypography format="h4" className={styles.Headline}>
          {t("settings.notification")}
        </IxTypography>
        <IxToggle textOn={t("settings.toggle-on")} textOff={t("settings.toggle-off")}></IxToggle>
      </section>
      <section>
        <IxTypography format="h4" className={styles.Headline}>
          {t("settings.import-device")}
        </IxTypography>
        <IxUpload
          className={styles.Upload}
          i18nUploadFile={t("settings.upload-button")}
          selectFileText={t("settings.upload-text")}
        ></IxUpload>
      </section>
    </section>
  );
}

// apps/vue-starter/src/components/Settings/ApplicationSettings.vue
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

<script setup lang="ts">
import { IxTypography, IxToggle, IxUpload } from "@siemens/ix-vue";
import { useI18n } from "vue-i18n";

const { t } = useI18n();
</script>

<template>
  <section class="ApplicationSettings">
    <section>
      <IxTypography format="h4" class="HeadlineSettings">{{ t("settings.notification") }}</IxTypography>
      <IxToggle :text-off="t('settings.toggle-off')" :text-on="t('settings.toggle-on')"></IxToggle>
    </section>
    <section>

      <IxTypography format="h4" class="HeadlineSettings">{{ t("settings.import-device") }}</IxTypography>
      <div class="file-upload-area">
        <IxUpload :select-file-text="t('settings.upload-text')" :i-1-8n-upload-file="t('settings.upload-button')" />
      </div>
    </section>
  </section>
</template>

<style scoped>
.notification-settings {
  justify-content: space-between;
  align-items: center;
  gap: 1.5rem;
}

.file-upload-area {
  width: 400px;
  height: 64px;
  padding-left: 0;
}

.ApplicationSettings {
  display: flex;
  flex-direction: column;
  gap: 1.5rem;
}

.HeadlineSettings {
  margin-bottom: 0.75rem;
}
</style>
