// apps/angular-starter/src/app/error-boundary.component.ts
import { Component, signal } from '@angular/core';
import { IxTypography, IxButton } from '@siemens/ix-angular/standalone';

@Component({
  selector: 'app-error-boundary',
  standalone: true,
  imports: [IxTypography, IxButton],
  templateUrl: './error-boundary.component.html',
  styleUrl: './error-boundary.component.css',
})
export class ErrorBoundaryComponent {
  error = signal<Error | null>(null);

  reload() {
    globalThis.location.reload();
  }
}

@if (error()) {
  <div class="error-boundary" role="alert" aria-live="assertive">
    <ix-typography format="h1" class="title">
      Something went wrong
    </ix-typography>
    <ix-typography format="body" class="message">
      {{ error()?.message || 'An unexpected error occurred' }}
    </ix-typography>
    <ix-button variant="primary" class="reload-button" aria-label="Reload page" (click)="reload()">
      Reload Page
    </ix-button>
  </div>
} @else {
  <ng-content />
}

// apps/vue-starter/src/components/ErrorBoundary.vue
<script setup lang="ts">
import { ref, onErrorCaptured } from 'vue';
import { IxTypography, IxButton } from '@siemens/ix-vue';

const error = ref<Error | null>(null);

onErrorCaptured((err: Error) => {
  console.error('Vue error caught by boundary:', err);
  error.value = err;
  return false;
});

function reload() {
  globalThis.location.reload();
}
</script>

<template>
  <div v-if="error" class="error-boundary" role="alert" aria-live="assertive">
    <IxTypography format="h1" class="title">
      Something went wrong
    </IxTypography>
    <IxTypography format="body" class="message">
      {{ error.message || 'An unexpected error occurred' }}
    </IxTypography>
    <IxButton variant="primary" class="reload-button" aria-label="Reload page" @click="reload">
      Reload Page
    </IxButton>
  </div>
  <slot v-else />
</template>

<style scoped src="./ErrorBoundary.css"></style>
