// apps/react-starter/src/pages/forms/Forms.tsx
/*
 * Copyright (c) Siemens 2018 - 2026
 * SPDX-License-Identifier: MIT
 */

import { useState } from 'react';
import {
  IxInput,
  IxSelect,
  IxSelectItem,
  IxDateInput,
  IxRadioGroup,
  IxRadio,
  IxButton,
  IxContentHeader,
  IxTypography,
  showMessage,
} from '@siemens/ix-react';
import styles from './Forms.module.css';
import { iconQuestion } from '@siemens/ix-icons/icons';

function Forms() {
  const [inspectorName, setInspectorName] = useState('');
  const [inspectionType, setInspectionType] = useState('');
  const [inspectionDate, setInspectionDate] = useState('');
  const [inspectionMode, setInspectionMode] = useState('inline');

  const handleSave = async () => {
    await showMessage({
      messageTitle: 'Confirm inspection assignment?',
      message: 'The inspection will be assigned and a notification will be sent to the inspector.',
      icon: iconQuestion,
      centered: true,
      actions: [
        { id: 'cancel', text: 'Cancel', type: 'cancel' },
        { id: 'ok', text: 'Confirm', type: 'okay' },
      ],
    });
  };

  return (
    <>
      <IxContentHeader headerTitle="Forms" />
      <IxTypography format="body" className={styles.description}>
        Siemens Industrial Experience provides consistent form elements for collecting and
        validating user input.
      </IxTypography>

      <form
        className={styles.formContainer}
        aria-label="Inspection assignment form"
        onSubmit={e => e.preventDefault()}
      >
        <IxInput
          label="Inspector Name"
          placeholder="Jane Doe"
          helperText="Enter the certified inspector's full name"
          value={inspectorName}
          onValueChange={e => setInspectorName(e.detail)}
        />

        <IxSelect
          label="Inspection Type"
          helperText="Choose the inspection to perform"
          value={inspectionType}
          onValueChange={e => setInspectionType(e.detail as string)}
        >
          <IxSelectItem value="Visual Inspection" label="Visual Inspection" />
          <IxSelectItem value="Dimensional Check" label="Dimensional Check" />
          <IxSelectItem value="Functional Test" label="Functional Test" />
          <IxSelectItem value="Safety Audit" label="Safety Audit" />
          <IxSelectItem value="Pressure Test" label="Pressure Test" />
          <IxSelectItem value="Material Analysis" label="Material Analysis" />
          <IxSelectItem value="Electrical Test" label="Electrical Test" />
          <IxSelectItem value="Thermal Imaging" label="Thermal Imaging" />
          <IxSelectItem value="Calibration Check" label="Calibration Check" />
        </IxSelect>

        <IxDateInput
          label="Inspection Date"
          helperText="Schedule the inspection"
          placeholder="DD/MM/YYYY"
          format="dd/MM/yyyy"
          value={inspectionDate}
          onValueChange={e => setInspectionDate(e.detail as string)}
        />

        <IxRadioGroup
          label="Inspection Mode"
          helperText="In-line inspection takes place during production. Offline sampling requires batch removal for lab testing."
          value={inspectionMode}
          onValueChange={e => setInspectionMode(e.detail as string)}
        >
          <IxRadio value="inline" label="In-line inspection" />
          <IxRadio value="offline" label="Offline sampling" />
        </IxRadioGroup>

        <div className={styles.buttonRow}>
          <IxButton variant="primary" aria-label="Save inspection assignment" onClick={handleSave}>
            {'Save'}
          </IxButton>
        </div>
      </form>
    </>
  );
}

export default Forms;

// packages/create-siemens-web/template-ix-angular-starter/src/pages/forms/forms.component.ts
/*
 * Copyright (c) Siemens 2018 - 2026
 * SPDX-License-Identifier: MIT
 */

import { Component, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import {
  IxContentHeader,
  IxTypography,
  IxInput,
  IxSelect,
  IxSelectItem,
  IxDateInput,
  IxRadioGroup,
  IxRadio,
  IxButton,
  MessageService,
} from '@siemens/ix-angular/standalone';
import { iconQuestion } from '@siemens/ix-icons/icons';

@Component({
  selector: 'app-forms-page',
  imports: [
    FormsModule,
    IxContentHeader,
    IxTypography,
    IxInput,
    IxSelect,
    IxSelectItem,
    IxDateInput,
    IxRadioGroup,
    IxRadio,
    IxButton,
  ],
  templateUrl: './forms.component.html',
  styleUrl: './forms.component.css',
})
export class FormsComponent {
  private readonly messageService = inject(MessageService);

  inspectorName = '';
  inspectionType = '';
  inspectionDate = '';
  inspectionMode = 'inline';

  onInspectionTypeChange(event: CustomEvent<string | string[]>) {
    const value = event.detail;
    this.inspectionType = Array.isArray(value) ? value[0] || '' : value;
  }

  onInspectionDateChange(event: CustomEvent<string | undefined>) {
    this.inspectionDate = event.detail || '';
  }

  async handleSave() {
    await this.messageService.showMessage({
      messageTitle: 'Confirm inspection assignment?',
      message: 'The inspection will be assigned and a notification will be sent to the inspector.',
      icon: iconQuestion,
      centered: true,
      actions: [
        { id: 'cancel', text: 'Cancel', type: 'cancel' },
        { id: 'ok', text: 'Confirm', type: 'okay' },
      ],
    });
  }
}

<ix-content-header headerTitle="Forms"></ix-content-header>
<ix-typography format="body" class="description">
  Siemens Industrial Experience provides consistent form elements for collecting and validating user
  input.
</ix-typography>

<form
  class="form-container"
  aria-label="Inspection assignment form"
  (submit)="$event.preventDefault()"
>
  <ix-input
    label="Inspector Name"
    placeholder="Jane Doe"
    helperText="Enter the certified inspector's full name"
    [value]="inspectorName"
    (valueChange)="inspectorName = $event.detail"
  ></ix-input>

  <ix-select
    label="Inspection Type"
    helperText="Choose the inspection to perform"
    [value]="inspectionType"
    (valueChange)="onInspectionTypeChange($event)"
  >
    <ix-select-item value="Visual Inspection" label="Visual Inspection"></ix-select-item>
    <ix-select-item value="Dimensional Check" label="Dimensional Check"></ix-select-item>
    <ix-select-item value="Functional Test" label="Functional Test"></ix-select-item>
    <ix-select-item value="Safety Audit" label="Safety Audit"></ix-select-item>
    <ix-select-item value="Pressure Test" label="Pressure Test"></ix-select-item>
    <ix-select-item value="Material Analysis" label="Material Analysis"></ix-select-item>
    <ix-select-item value="Electrical Test" label="Electrical Test"></ix-select-item>
    <ix-select-item value="Thermal Imaging" label="Thermal Imaging"></ix-select-item>
    <ix-select-item value="Calibration Check" label="Calibration Check"></ix-select-item>
  </ix-select>

  <ix-date-input
    label="Inspection Date"
    helperText="Schedule the inspection"
    placeholder="DD/MM/YYYY"
    format="dd/MM/yyyy"
    [value]="inspectionDate"
    (valueChange)="onInspectionDateChange($event)"
  ></ix-date-input>

  <ix-radio-group
    label="Inspection Mode"
    helperText="In-line inspection takes place during production. Offline sampling requires batch removal for lab testing."
    [value]="inspectionMode"
    (valueChange)="inspectionMode = $event.detail"
  >
    <ix-radio value="inline" label="In-line inspection"></ix-radio>
    <ix-radio value="offline" label="Offline sampling"></ix-radio>
  </ix-radio-group>

  <div class="button-row">
    <ix-button variant="primary" aria-label="Save inspection assignment" (click)="handleSave()"
      >Save</ix-button
    >
  </div>
</form>
