// apps/angular-starter/src/app/pages/overview/components/status-history/status-history.component.ts
import { Component, OnInit, ViewChild } from '@angular/core';
import {
  IxCard,
  IxCardContent,
  IxTypography,
} from '@siemens/ix-angular/standalone';
import { NgxEchartsDirective, provideEchartsCore } from 'ngx-echarts';
import { getComputedCSSProperty } from '@siemens/ix-echarts';
import * as echarts from 'echarts/core';
import { EChartsOption } from 'echarts';
import { LineChart } from 'echarts/charts';
import { TranslateModule } from '@ngx-translate/core';
import { BehaviorSubject } from 'rxjs';
import { themeSwitcher } from '@siemens/ix';
import { AsyncPipe } from '@angular/common';

echarts.use([LineChart]);

@Component({
  selector: 'status-history',
  imports: [
    IxCard,
    IxCardContent,
    IxTypography,
    NgxEchartsDirective,
    TranslateModule,
    AsyncPipe,
  ],
  templateUrl: './status-history.component.html',
  styleUrl: './status-history.component.scss',
  providers: [provideEchartsCore({ echarts })],
})
export class StatusHistoryComponent implements OnInit {
  @ViewChild(NgxEchartsDirective) chart!: NgxEchartsDirective;

  themeSubject = new BehaviorSubject<string>('theme-classic-dark');
  theme$ = this.themeSubject.asObservable();

  seriesOnline = {
    name: 'Online',
    color: getComputedCSSProperty('color-success'),
    data: [60, 75, 100, 60, 75, 60],
  };

  seriesOffline = {
    name: 'Offline',
    color: getComputedCSSProperty('color-neutral'),
    data: [-30, -62, -25, -61, -99, -60],
  };

  seriesErrors = {
    name: 'Errors',
    color: getComputedCSSProperty('color-alarm'),
    data: [0, 17, -39, -60, -20, -2],
  };

  seriesMaintenance = {
    name: 'Maintenance',
    color: getComputedCSSProperty('color-warning'),
    data: [0, 2, -90, -85, -3, -1],
  };

  options: EChartsOption = {
    legend: {
      show: true,
      bottom: '0',
      left: '0',
      icon: 'rect',
    },

    grid: {
      top: 10,
      bottom: 85,
      left: 40,
      right: 10,
    },

    xAxis: {
      type: 'category',
      data: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
      boundaryGap: false,
      splitLine: {
        show: true,
      },
    },
    yAxis: {
      type: 'value',
      splitLine: {
        show: true,
      },
    },
    series: [
      {
        type: 'line',
        ...this.seriesOnline,
      },
      {
        type: 'line',
        ...this.seriesMaintenance,
      },
      {
        type: 'line',
        ...this.seriesErrors,
      },
      {
        type: 'line',
        ...this.seriesOffline,
      },
    ],
  };

  constructor() {}

  ngOnInit(): void {
    themeSwitcher.themeChanged.on((theme: string) => {
      this.themeSubject.next(theme);
    });
  }
}

<ix-card class="status-history">
  <ix-card-content>
    <ix-typography format="label" bold>
      {{ "status-history.title" | translate }}
    </ix-typography>
    <div
      echarts
      [options]="options"
      [theme]="theme$ | async"
      class="echarts"
    ></div>
  </ix-card-content>
</ix-card>

// apps/react-starter/src/pages/overview/components/status-history/index.jsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import styles from "./styles.module.css";

import { IxCard, IxCardContent, IxTypography } from "@siemens/ix-react";
import { getComputedCSSProperty } from "@siemens/ix-echarts";
import ReactEcharts from "echarts-for-react";
const seriesOnline = {
  name: "Online",
  color: [getComputedCSSProperty("color-success")],
  areaStyle: {
    color: getComputedCSSProperty("color-success"),
    opacity: 0.4,
  },
  data: [
    { value: 60 },
    { value: 75 },
    { value: 100 },
    { value: 60 },
    { value: 75 },
    { value: 60 },
  ],
};

const seriesOffline = {
  name: "Offline",
  color: [getComputedCSSProperty("color-neutral")],
  areaStyle: {
    color: getComputedCSSProperty("color-neutral"),
    opacity: 0.4,
  },
  data: [
    { value: -30 },
    { value: -62 },
    { value: -25 },
    { value: -61 },
    { value: -99 },
    { value: -60 },
  ],
};

const seriesErrors = {
  name: "Errors",
  color: getComputedCSSProperty("color-alarm"),
  areaStyle: {
    color: getComputedCSSProperty("color-alarm"),
    opacity: 0.4,
  },
  data: [
    { value: 0 },
    { value: 17 },
    { value: -39 },
    { value: -60 },
    { value: -20 },
    { value: -2 },
  ],
};

function getOption() {
  return {
    legend: {
      orient: "horizontal",
      icon: "rect",
      left: "1",
      bottom: "1",
      textStyle: {
        color: getComputedCSSProperty("color-std-text"),
      },
    },
    xAxis: {
      data: ["Jan", "Feb", "Mar", "Apr", "May", "Jun"],
    },
    yAxis: {},
    series: [
      {
        type: "line",
        label: {
          show: false,
          color: getComputedCSSProperty("color-neutral"),
        },
        ...seriesOnline,
      },
      {
        type: "line",
        label: {
          show: false,
          color: getComputedCSSProperty("color-neutral"),
        },
        ...seriesErrors,
      },
      {
        type: "line",
        label: {
          show: false,
          color: getComputedCSSProperty("color-neutral"),
        },
        ...seriesOffline,
      },
    ],
  };
}

function StatusHistory() {
  return (
    <IxCard>
      <IxCardContent>
        <IxTypography format="h3">Status history</IxTypography>
        <ReactEcharts className={styles.echarts} option={getOption()} />
      </IxCardContent>
    </IxCard>
  );
}

export default StatusHistory;
