// apps/react-starter/src/pages/grids/Grids.tsx
/*
 * Copyright (c) Siemens 2018 - 2026
 * SPDX-License-Identifier: MIT
 */

import { IxTypography, IxContentHeader } from '@siemens/ix-react';
import { AgGridReact } from 'ag-grid-react';
import * as ag from 'ag-grid-community';
import { getIxTheme } from '@siemens/ix-aggrid';
import { GRID_ROW_DATA, GRID_COL_DEFS } from '../../shared';
import styles from './Grids.module.css';

const ixTheme = getIxTheme(ag);

function Grids() {
  return (
    <>
      <IxContentHeader headerTitle="Grids" />
      <IxTypography format="body" className={styles.description}>
        Siemens Industrial Experience integrates the data grid library{' '}
        <a
          href="https://www.ag-grid.com"
          target="_blank"
          rel="noreferrer"
          aria-label="AG Grid (opens in a new tab)"
        >
          AG Grid
        </a>
        .<br />
        This lets you use its features while staying consistent with the Siemens Industrial
        Experience design system.
      </IxTypography>

      <section className={styles.gridContainer} aria-label="Inspection data grid">
        <AgGridReact
          rowData={GRID_ROW_DATA}
          columnDefs={GRID_COL_DEFS}
          suppressMovableColumns={true}
          domLayout="autoHeight"
          theme={ixTheme}
          aria-label="Inspection records table"
        />
      </section>
    </>
  );
}

export default Grids;

// packages/create-siemens-web/template-ix-angular-starter/src/pages/grids/grids.component.ts
/*
 * Copyright (c) Siemens 2018 - 2026
 * SPDX-License-Identifier: MIT
 */

import { Component } from '@angular/core';
import { IxContentHeader, IxTypography } from '@siemens/ix-angular/standalone';
import { AgGridAngular } from 'ag-grid-angular';
import * as ag from 'ag-grid-community';
import { ColDef } from 'ag-grid-community';
import { getIxTheme } from '@siemens/ix-aggrid';
import { GRID_ROW_DATA, GRID_COL_DEFS, type GridRowData } from './../../shared';

@Component({
  selector: 'app-grids',
  imports: [IxContentHeader, IxTypography, AgGridAngular],
  templateUrl: './grids.component.html',
  styleUrl: './grids.component.css',
})
export class GridsComponent {
  protected readonly ixTheme = getIxTheme(ag);

  rowData = GRID_ROW_DATA;

  columnDefs: ColDef<GridRowData>[] = GRID_COL_DEFS;
}
