// apps/react-starter/src/pages/get-started/GetStarted.tsx
import { useNavigate } from 'react-router-dom';
import { IxTypography, IxLinkButton, IxContentHeader } from '@siemens/ix-react';
import styles from './GetStarted.module.css';

function GetStarted() {
  const navigate = useNavigate();

  return (
    <>
      <IxContentHeader headerTitle="Get started with Siemens Industrial Experience" />
      <IxTypography format="body" className={styles.description}>
        Explore the Siemens Industrial Experience design system with our interactive starter app.
        <br />
        Build faster with ready-to-use components and documentation.
      </IxTypography>

      <IxTypography format="body" className={styles.descriptionShort}>
        The starter app includes an application shell and three example pages featuring our most
        popular components:
      </IxTypography>

      <div className={styles.navLinks}>
        <IxLinkButton onClick={() => navigate('/forms')} aria-label="Navigate to Forms page">
          Forms
        </IxLinkButton>
        <IxLinkButton onClick={() => navigate('/charts')} aria-label="Navigate to Charts page">
          Charts
        </IxLinkButton>
        <IxLinkButton onClick={() => navigate('/grids')} aria-label="Navigate to Grids page">
          Grids
        </IxLinkButton>
      </div>

      <IxTypography format="body" className={styles.description}>
        Browse the full component library in our documentation:{' '}
        <a
          href="https://ix.siemens.io"
          target="_blank"
          rel="noreferrer"
          aria-label="ix.siemens.io (opens in a new tab)"
        >
          ix.siemens.io
        </a>
      </IxTypography>
    </>
  );
}

export default GetStarted;

// apps/vue-starter/src/pages/get-started/GetStarted.vue
<script setup lang="ts">
import { useRouter } from 'vue-router';
import { IxContentHeader, IxTypography, IxLinkButton } from '@siemens/ix-vue';

const router = useRouter();
</script>

<template>
  <IxContentHeader header-title="Get started with Siemens Industrial Experience" />
  <IxTypography format="body" class="description">
    Explore the Siemens Industrial Experience design system with our interactive starter app.
    <br />
    Build faster with ready-to-use components and documentation.
  </IxTypography>

  <IxTypography format="body" class="description-short">
    The starter app includes an application shell and three example pages featuring our most popular
    components:
  </IxTypography>

  <div class="nav-links">
    <IxLinkButton aria-label="Navigate to Forms page" @click.prevent="router.push('/forms')"
      >Forms</IxLinkButton
    >
    <IxLinkButton aria-label="Navigate to Charts page" @click.prevent="router.push('/charts')"
      >Charts</IxLinkButton
    >
    <IxLinkButton aria-label="Navigate to Grids page" @click.prevent="router.push('/grids')"
      >Grids</IxLinkButton
    >
  </div>

  <IxTypography format="body" class="description">
    Browse the full component library in our documentation:
    <a
      href="https://ix.siemens.io"
      target="_blank"
      rel="noreferrer"
      aria-label="ix.siemens.io (opens in a new tab)"
    >
      ix.siemens.io
    </a>
  </IxTypography>
</template>

<style scoped src="./GetStarted.css"></style>
