// apps/vue-starter/src/pages/get-started/GetStarted.vue
<!--
  ~ Copyright (c) Siemens 2018 - 2026
  ~ SPDX-License-Identifier: MIT
-->

<script setup lang="ts">
import { useRouter } from 'vue-router';
import { IxContentHeader, IxTypography, IxLinkButton } from '@siemens/ix-vue';

const router = useRouter();
</script>

<template>
  <IxContentHeader header-title="Get started with Siemens Industrial Experience" />
  <IxTypography format="body" class="description">
    Explore the Siemens Industrial Experience design system with our interactive starter app.
    <br />
    Build faster with ready-to-use components and documentation.
  </IxTypography>

  <IxTypography format="body" class="description-short">
    The starter app includes an application shell and three example pages featuring our most popular
    components:
  </IxTypography>

  <div class="nav-links">
    <IxLinkButton aria-label="Navigate to Forms page" @click.prevent="router.push('/forms')"
      >Forms</IxLinkButton
    >
    <IxLinkButton aria-label="Navigate to Charts page" @click.prevent="router.push('/charts')"
      >Charts</IxLinkButton
    >
    <IxLinkButton aria-label="Navigate to Grids page" @click.prevent="router.push('/grids')"
      >Grids</IxLinkButton
    >
  </div>

  <IxTypography format="body" class="description">
    Browse the full component library in our documentation:
    <a
      href="https://ix.siemens.io"
      target="_blank"
      rel="noreferrer"
      aria-label="ix.siemens.io (opens in a new tab)"
    >
      ix.siemens.io
    </a>
  </IxTypography>
</template>

<style scoped src="./GetStarted.css"></style>

// packages/create-siemens-web/template-ix-angular-starter/src/pages/get-started/get-started.component.ts
/*
 * Copyright (c) Siemens 2018 - 2026
 * SPDX-License-Identifier: MIT
 */

import { Component, inject } from '@angular/core';
import { Router } from '@angular/router';
import { IxContentHeader, IxTypography, IxLinkButton } from '@siemens/ix-angular/standalone';

@Component({
  selector: 'app-get-started',
  imports: [IxContentHeader, IxTypography, IxLinkButton],
  templateUrl: './get-started.component.html',
  styleUrl: './get-started.component.css',
})
export class GetStartedComponent {
  private readonly router = inject(Router);

  navigate(path: string) {
    this.router.navigate([path]);
  }
}

<div>
  <ix-content-header
    headerTitle="Get started with Siemens Industrial Experience"
  ></ix-content-header>
  <ix-typography format="body" class="description">
    Explore the Siemens Industrial Experience design system with our interactive starter app.
    <br />
    Build faster with ready-to-use components and documentation.
  </ix-typography>

  <ix-typography format="body" class="description-short">
    The starter app includes an application shell and three example pages featuring our most popular
    components:
  </ix-typography>

  <div class="nav-links">
    <ix-link-button (click)="navigate('/forms')" aria-label="Navigate to Forms page"
      >Forms</ix-link-button
    >
    <ix-link-button (click)="navigate('/charts')" aria-label="Navigate to Charts page"
      >Charts</ix-link-button
    >
    <ix-link-button (click)="navigate('/grids')" aria-label="Navigate to Grids page"
      >Grids</ix-link-button
    >
  </div>

  <ix-typography format="body" class="description">
    Browse the full component library in our documentation:
    <a
      href="https://ix.siemens.io"
      target="_blank"
      rel="noreferrer"
      aria-label="ix.siemens.io (opens in a new tab)"
      >ix.siemens.io</a
    >
  </ix-typography>
</div>
